### ISSUE TITLE
Migration requires config in console

### ISSUE THREAD

**Issue by Eseperio** [macklus/yii2-payments#1]
Running migration on console throws an error if module is not loaded in console configuration.

**Comment by macklus** [comment]
Hi @Eseperio 
I can confirm i got no console config on the apps where i use this plugin.
Even that, i add to documentation install page info about migration command.

Can you please send me the error message or more info to try to reproduce it ?

thanks in advance

**Comment by Eseperio** [comment]
I was using advanced app boilerplate

**Comment by macklus** [comment]
Not sure if this is bug or i misunderstand.
Please, post here commands you use, and error you get.
thanks

**Comment by GlyphDataServices** [comment]
Following your install instructions results in an error because the module is not loaded, so the migrations can't get the table names.  Hard-coding them as a workaround.  
```
Apply the above migrations? (yes|no) [no]:y
*** applying m170807_072112_add_payments_table
    > create table  ...Exception: SQLSTATE[42601]: Syntax error: 7 ERROR:  zero-length delimited identifier at or near """"
LINE 1: CREATE TABLE "" (
                     ^
The SQL being executed was: CREATE TABLE "" (
	"id" INT(11) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
	"code" VARCHAR(32) NOT NULL,
	"item" VARCHAR(255) NOT NULL,
	"amount" FLOAT(10,2) NOT NULL,
	"provider" ENUM("paypal", "redsys", "transfer") NOT NULL,
	"date_received" TIMESTAMP DEFAULT 0,
	"date_procesed" TIMESTAMP DEFAULT 0,
	"date_add" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	"date_edit" TIMESTAMP DEFAULT 0
) (/var/www/html/bioreactor/pub2/vendor/yiisoft/yii2/db/Schema.php:594)
#0 /var/www/html/bioreactor/pub2/vendor/yiisoft/yii2/db/Command.php(1004): yii\db\Schema->convertException(Object(PDOException), 'CREATE TABLE ""...')

```

**Comment by macklus** [comment]
Error where on docs.
If you dont configure console.php **before** run migrations, it hangs because it cannt find tablenames, as you report.

Version 1.0.2 fix this by detailed install and configuration of plugin.

Sorry about previous misunderstanding
