### ISSUE TITLE
deprecated cause migration issue

### ISSUE THREAD

**Issue by paskuale75** [macklus/yii2-payments#10]
Hi @macklus thanks for this repo, in the $ payments array you should comment on the two lines:

```
.....
//'logDir' => '@runtime/payments',
//'logDirPerms' => 0755,
.....
```

otherwise as soon as the migrate command is issued, the error returns _throw new OldConfigurationValueException();_ from Bootstrap.php file on line 29.

**Comment by macklus** [comment]
@paskuale75 , please can you post a simple example about it ?
what version of Yii are you running ?

thanks in advance

**Comment by paskuale75** [comment]
Yii 2.0.36

**Comment by macklus** [comment]
I not sure about the related problem.
Interesting code is on https://github.com/macklus/yii2-payments/blob/7072710a2ee94a21afd0c9bbac379a18d58aff53/Bootstrap.php#L28

```
if ((isset($module->logDir) && $module->logDir != 'deprecated') || (isset($module->logDirPerms) && $module->logDirPerms != 'deprecated')) {
            throw new OldConfigurationValueException();
        }
```
that means, if variables logDir and logDirPerms are defined and they value are not "deprecated", we throw the exception. Variables are still defined to avoid problems with older versions.

So if you have this problem, i understood that you have this variables defined in your config file, with other values.

Can you please post your config on this module ?

**Comment by paskuale75** [comment]
I have currently commented on them, here it is:
```
return [
    'class' => 'macklus\payments\PaymentsModule',
    'urlPrefix' => '/payments',
    //'logDir' => '@runtime/payments',
    //'logDirPerms' => 0755,
    'tables' => [
        'payment' => 'payment',
        'response' => 'payment_response',
    ],
```

**Comment by macklus** [comment]
So, problem is dissapear ? or still remain ?
if you add;
```
echo ($module->logDir . ' ' . $module->logDirPerms );
```

before line 28 in yii2-payments/Bootstrap.php, wich values it returns ?

**Comment by paskuale75** [comment]
do I have to uncomment lines first?

**Comment by macklus** [comment]
No, it isn neccesary. If this options are commented on your plugin config, everithing should run fine. otherwise, try the echo command to see what values has.

**Comment by paskuale75** [comment]
sorry for the delay in replying, it print to me 

`deprecated deprecated`

**Comment by macklus** [comment]
@paskuale75 as both variables has deprecated value, it dont should throw any exception. is the problem solved ?
if not, please share with me your proyect so i can look futher
