### ISSUE TITLE
Undefined class constant 'PROVIDER_PAYPAL'

### ISSUE THREAD

**Issue by neoacevedo** [macklus/yii2-payments#4]
This error happens on this line:
`$payment->start(Payment::PROVIDER_PAYPAL);`

This constant is found on *PaymentModel*

**Comment by neoacevedo** [comment]
Can be replaced with `$payment->start('paypal');`

**Comment by macklus** [comment]
Looking on this. Maybe is a bad docs problem.

**Comment by macklus** [comment]
Problem is about defined constants.
Class macklus\payments\Payment.php have not defined constants, that are already defined on other class.

Should be defined two Interfaces to handle all constans and implements on different classes.
