### ISSUE TITLE
String data, right truncated: 1406 Data too long for column 'code' at row 1

### ISSUE THREAD

**Issue by neoacevedo** [macklus/yii2-payments#5]
Usando el código de ejemplo arroja el siguiente error:
```
String data, right truncated: 1406 Data too long for column 'code' at row 1
The SQL being executed was: INSERT INTO `payment` (`provider`, `amount`, `item`, `code`, `date_add`, `date_edit`) VALUES ('paypal', 12, 'ADJCADFAD', '5CC29E9B-B504-436A-8626-7BACE4A82638', NOW(), NOW())
```
Verificando el atributo **_code_** de la tabla **payment**, este es un varchar de 32 caracteres y obviamente, el código autogenerado supera dicha longitud.

**Comment by macklus** [comment]
@neoacevedo ¿Qué ejemplo de qué proveedor has probado?

**Comment by macklus** [comment]
@neoacevedo mirando el código, el error que me comentas no debería aparecer (el modelo Payment tiene como condición:
```
[['code'], 'string', 'max' => 32],
```
¿Puedo ver el código que estás usando? ¿Qué bbdd estás usando?

**Comment by neoacevedo** [comment]
Hola, el ejemplo probado es de Paypal. Lo tomé del ejemplo original. 
```
$payment = new Payment();
        $payment->start('paypal');
        $payment->setAmount((float)12);
        $payment->setName("pedido");
        $payment->setItem('ADJCADFAD');
        $payment->setUrlOK(\yii\helpers\Url::to(['/member/payment/success']));
        $payment->setUrlError(\yii\helpers\Url::to(['/site/error']));

        $submitButton = Html::submitButton('Enviar', ['class' => 'btn btn-default']);
        $payment->setParameter('submit', $submitButton);
        $payment->setParameter('form_target', '_blank');
        
        $payment->process();
        \Yii::$app->language = \Yii::$app->request->getPreferredLanguage(Yii::$app->params['preferredLanguages']);
        echo $payment->renderForm('paypal', ['payment' => $payment]);
        
        $payment->end();
```
Pero estaba viendo lo siguiente en **Payment** en el método **_beforeSave_**:
`$this->code = strtoupper(Uuid::uuid4()->toString());`
Acá se genera el código, pero la cadena generada es de 37 caracteres.

Olvidaba: estoy usando MariaDB, en Yii2 Advanced.

**Comment by macklus** [comment]
@neoacevedo desde una app yii2 básica recién instalada, el error no aparece.
Confírmame que tienes la última versión del plugin 1.0.2 (constante VERSION en PaymentsModule.php)

En cualquier caso, la forma más sencilla de evitar el problema es limitar el tamaño de la cadena generada a 32 caracteres.

**Comment by neoacevedo** [comment]
@macklus yo estoy usando la plantilla avanzada. Y, de acuerdo a las instrucciones de instalación, debería estar usando la última versión la cual confirmo. 

Para limitar el tamaño, se haría desde la propia extensión. Lo hice, aunque el producto en desarrollo se distribuye sin el directorio Vendor.

**Comment by macklus** [comment]
La versión 1.0.3 contiene el commit https://github.com/macklus/yii2-payments/commit/a7e2750c8376a3077b9207d63e012689095164f3 , que evita que se generen códigos de más de 32 caracteres. Con actualizar no debería pasarte de nuevo
